### PR TITLE
Format bubble value & updatePositionOnTap

### PR DESCRIPTION
**Pull request by ltdangkhoa**
Hi,

I've added 2 new options for this package:

1. The ability to format value in bubble indicator by using NumberFormat from intl package: Eg: 123456789.01 -> 123,456,789.01

2. While experience current package, I've found that the long press gesture to display bubble indicator on each point would not easy for end-user. The option updatePositionOnTap will solve that problem. However, there is a trade off with the ability to hide the indicator.

Above options are optional and keep the default behavior from master repository

Thanks

### CODE REVIEW

**Comment by diegoveloper** [comment]
Great, please add a new sample in the example project using the new properties you added.

**Comment by ltdangkhoa** [comment]
> Great, please add a new sample in the example project using the new properties you added.

Can I update to the sample13?

**Comment by diegoveloper** [comment]
Or you can create sample14

**Comment by ltdangkhoa** [comment]
@diegoveloper : new sample have been added ;)

**Comment by diegoveloper** [comment]
Thanks @ltdangkhoa  it looks great! one thing before merging it , change the PR to dev instead of master.

**Comment by ltdangkhoa** [comment]
@diegoveloper Is it ok for the dev branch?

**Comment by diegoveloper** [comment]
Yes, point to dev branch, it looks like it has some conflicts

**Comment by diegoveloper** [comment]
@ltdangkhoa please check the conflicting files before the merge

**Comment by ltdangkhoa** [comment]
@diegoveloper Sorry I'm not good at git merging. Is it okay right now?

**Comment by diegoveloper** [comment]
@ltdangkhoa thanks !!

**Comment by davidkalil10** [comment]
You're awesome guys!! Is already possible to use this new features? where can i found some examples?

**Pull request merged**
