### PR TITLE
Fix when using BezierChartScale.WEEKLY

### PR DESCRIPTION
**Pull request by delay**
Here is the sample of the problem with the fix.  I modified sample 3 in your examples.  https://github.com/delay/bezier-chart I also made the fix for the problem.  I did not fix the third issue I mentioned but this will handle the first two problems I mentioned.  You will notice if you run your current version of the library it will not show any points.  However in the fixed code it correctly displays the two points on the graph.  The example changes are just to show you the problem.  They are not part of the code change I am suggesting.

### CODE REVIEW

**Comment by diegoveloper** [comment]
Hi @delay , thanks for the PR, just to avoid modifying the current `sample3` , could you create another sample in the `main.dart` file (sample9 could be) ?

**Comment by delay** [comment]
ok will do.  I didn't really want the example to be merged, it was just to demonstrate the bug.

**Comment by delay** [comment]
ok set up a separate sample 9 to demonstrate problem.

**Comment by diegoveloper** [comment]
Ok, I will check today later , thanks !!

**Pull request merged**
